import type { ReliefCategoryRule } from '@/lib/reliefs/types'

/**
 * Malaysia individual tax relief categories (YA 2025).
 * Source: `tax_relief_rules_2025.md` in repo root.
 */
export const YA2025_RULES: ReliefCategoryRule[] = [
  {
    id: 'individual_dependent_relatives',
    year: 2025,
    docSection: '§1',
    name: 'Individual and dependent relatives',
    description:
      'Automatic individual relief and dependent relatives (per statutory rules).',
    limit: { kind: 'fixed', amountRm: 9000 },
    category: 'other',
    icon: 'person',
    taxSectionHint: 'YA 2025 · §1',
  },
  {
    id: 'parents_grandparents_medical_care',
    year: 2025,
    docSection: '§2',
    name: 'Parents and grandparents (medical and care)',
    description:
      'Medical, dental, special needs, and carer expenses (medical condition certified). Complete medical examination counts toward the same total with a lower sub-limit.',
    limit: {
      kind: 'cappedSum',
      capRm: 8000,
      subcaps: [
        {
          id: 'complete_medical_exam',
          label: 'Complete medical examination',
          capRm: 1000,
        },
      ],
    },
    category: 'parental',
    icon: 'groups',
    taxSectionHint: 'YA 2025 · §2',
  },
  {
    id: 'basic_supporting_equipment_disabled',
    year: 2025,
    docSection: '§3',
    name: 'Basic supporting equipment (disabled)',
    description:
      'For disabled self, spouse, child, or parent — supporting equipment.',
    limit: { kind: 'fixed', amountRm: 6000 },
    category: 'medical',
    icon: 'accessible',
    taxSectionHint: 'YA 2025 · §3',
  },
  {
    id: 'disabled_individual',
    year: 2025,
    docSection: '§4',
    name: 'Disabled individual',
    description: 'Relief for an individual certified as disabled.',
    limit: { kind: 'fixed', amountRm: 7000 },
    category: 'other',
    icon: 'accessible',
    taxSectionHint: 'YA 2025 · §4',
  },
  {
    id: 'education_fees_self',
    year: 2025,
    docSection: '§5',
    name: 'Education fees (self)',
    description:
      'Non-masters/PhD: law, accounting, Islamic financing, technical, vocational, industrial, scientific, or technology courses. Masters/PhD: any course. Upskilling/self-enhancement within a sub-limit.',
    limit: {
      kind: 'cappedSum',
      capRm: 7000,
      subcaps: [
        {
          id: 'upskilling_self_enhancement',
          label: 'Upskilling / self-enhancement',
          capRm: 2000,
        },
      ],
    },
    category: 'education',
    icon: 'school',
    taxSectionHint: 'YA 2025 · §5',
  },
  {
    id: 'medical_serious_conditions',
    year: 2025,
    docSection: '§6',
    name: 'Medical expenses (serious conditions)',
    description:
      'Serious diseases (self, spouse, child), fertility treatment (self or spouse), vaccination, and dental examination/treatment within sub-limits.',
    limit: {
      kind: 'cappedSum',
      capRm: 10000,
      subcaps: [
        { id: 'vaccination', label: 'Vaccination', capRm: 1000 },
        {
          id: 'dental_exam_treatment',
          label: 'Dental examination and treatment',
          capRm: 1000,
        },
      ],
    },
    category: 'medical',
    icon: 'health_and_safety',
    taxSectionHint: 'YA 2025 · §6',
  },
  {
    id: 'health_screening_tests',
    year: 2025,
    docSection: '§7',
    name: 'Health screening and tests',
    description:
      'Complete medical examination, COVID-19 detection tests, mental health consultation, self-health monitoring equipment, disease detection tests.',
    limit: { kind: 'fixed', amountRm: 1000 },
    category: 'medical',
    icon: 'monitor_heart',
    taxSectionHint: 'YA 2025 · §7',
  },
  {
    id: 'child_development_u18',
    year: 2025,
    docSection: '§8',
    name: 'Child development (≤ 18 years old)',
    description:
      'Intellectual disability assessment, early intervention and rehabilitation programmes.',
    limit: { kind: 'fixed', amountRm: 6000 },
    category: 'parental',
    icon: 'child_care',
    taxSectionHint: 'YA 2025 · §8',
  },
  {
    id: 'lifestyle_general',
    year: 2025,
    docSection: '§9',
    name: 'Lifestyle (general)',
    description:
      'Books, journals, magazines; personal computer, smartphone, tablet (non-business); internet subscription (own name); skill improvement courses.',
    limit: { kind: 'fixed', amountRm: 2500 },
    category: 'lifestyle',
    icon: 'devices',
    taxSectionHint: 'YA 2025 · §9',
  },
  {
    id: 'lifestyle_sports',
    year: 2025,
    docSection: '§10',
    name: 'Lifestyle (sports)',
    description:
      'Sports equipment, rental/entry fees for sports facilities, competition registration (approved organisers), gym membership/training.',
    limit: { kind: 'fixed', amountRm: 1000 },
    category: 'lifestyle',
    icon: 'fitness_center',
    taxSectionHint: 'YA 2025 · §10',
  },
  {
    id: 'breastfeeding_equipment',
    year: 2025,
    docSection: '§11',
    name: 'Breastfeeding equipment',
    description:
      'For child aged ≤ 2 years. Claimable once every 2 years (eligibility rules apply).',
    limit: { kind: 'fixed', amountRm: 1000 },
    category: 'other',
    icon: 'child_friendly',
    taxSectionHint: 'YA 2025 · §11',
  },
  {
    id: 'child_care_fees',
    year: 2025,
    docSection: '§12',
    name: 'Child care fees',
    description:
      'Registered childcare centre or kindergarten; child aged ≤ 6 years.',
    limit: { kind: 'fixed', amountRm: 3000 },
    category: 'parental',
    icon: 'child_care',
    taxSectionHint: 'YA 2025 · §12',
  },
  {
    id: 'sspn_education_savings',
    year: 2025,
    docSection: '§13',
    name: 'SSPN (education savings)',
    description:
      'Net deposit = total deposit minus total withdrawal in the same year.',
    limit: { kind: 'fixed', amountRm: 8000 },
    category: 'education',
    icon: 'savings',
    taxSectionHint: 'YA 2025 · §13',
  },
  {
    id: 'spouse_alimony',
    year: 2025,
    docSection: '§14',
    name: 'Spouse / alimony',
    description: 'Husband, wife, or alimony to former wife.',
    limit: { kind: 'fixed', amountRm: 4000 },
    category: 'other',
    icon: 'favorite',
    taxSectionHint: 'YA 2025 · §14',
  },
  {
    id: 'disabled_spouse',
    year: 2025,
    docSection: '§15',
    name: 'Disabled spouse',
    description: 'Spouse certified as disabled.',
    limit: { kind: 'fixed', amountRm: 6000 },
    category: 'other',
    icon: 'group',
    taxSectionHint: 'YA 2025 · §15',
  },
  {
    id: 'child_under_18',
    year: 2025,
    docSection: '§16a',
    name: 'Child (< 18 years old)',
    description: 'Per qualifying child under 18.',
    limit: {
      kind: 'perUnit',
      amountRm: 2000,
      unitLabel: 'qualifying child under 18',
    },
    category: 'parental',
    icon: 'family_restroom',
    taxSectionHint: 'YA 2025 · §16a',
  },
  {
    id: 'child_18_preuniversity',
    year: 2025,
    docSection: '§16b',
    name: 'Child (≥ 18, full-time pre-university)',
    description:
      'Unmarried child studying full-time pre-university (e.g. A-Level, matriculation).',
    limit: {
      kind: 'perUnit',
      amountRm: 2000,
      unitLabel: 'qualifying child (pre-university)',
    },
    category: 'parental',
    icon: 'school',
    taxSectionHint: 'YA 2025 · §16b(i)',
  },
  {
    id: 'child_18_tertiary',
    year: 2025,
    docSection: '§16b',
    name: 'Child (≥ 18, full-time tertiary)',
    description:
      'Diploma or higher in Malaysia, or degree or higher overseas at approved institutions.',
    limit: {
      kind: 'perUnit',
      amountRm: 8000,
      unitLabel: 'qualifying child (tertiary)',
    },
    category: 'parental',
    icon: 'school',
    taxSectionHint: 'YA 2025 · §16b(ii)',
  },
  {
    id: 'disabled_child',
    year: 2025,
    docSection: '§16c',
    name: 'Disabled child',
    description:
      'Base relief RM 8,000 per disabled child; additional RM 8,000 when aged ≥ 18 and studying full-time diploma or higher (per rules).',
    limit: { kind: 'fixed', amountRm: 16000 },
    category: 'parental',
    icon: 'accessible',
    taxSectionHint: 'YA 2025 · §16c',
  },
  {
    id: 'life_insurance_epf',
    year: 2025,
    docSection: '§17',
    name: 'Life insurance and EPF',
    description:
      'Combined relief for EPF contributions and life insurance / takaful within pool limits.',
    limit: {
      kind: 'splitPool',
      totalCapRm: 7000,
      pools: [
        { id: 'epf', label: 'EPF contributions', capRm: 4000 },
        { id: 'life_takaful', label: 'Life insurance / takaful', capRm: 3000 },
      ],
    },
    category: 'epf',
    icon: 'savings',
    taxSectionHint: 'YA 2025 · §17',
  },
  {
    id: 'deferred_annuity_prs',
    year: 2025,
    docSection: '§18',
    name: 'Deferred annuity and PRS',
    description: 'Deferred annuity scheme and Private Retirement Scheme (PRS).',
    limit: { kind: 'fixed', amountRm: 3000 },
    category: 'other',
    icon: 'account_balance',
    taxSectionHint: 'YA 2025 · §18',
  },
  {
    id: 'education_medical_insurance',
    year: 2025,
    docSection: '§19',
    name: 'Education and medical insurance',
    description: 'Premiums for education and medical insurance / takaful.',
    limit: { kind: 'fixed', amountRm: 4000 },
    category: 'medical',
    icon: 'medical_services',
    taxSectionHint: 'YA 2025 · §19',
  },
  {
    id: 'socso_contribution',
    year: 2025,
    docSection: '§20',
    name: 'SOCSO contribution',
    description: 'SOCSO (PERKESO) contributions.',
    limit: { kind: 'fixed', amountRm: 350 },
    category: 'other',
    icon: 'shield',
    taxSectionHint: 'YA 2025 · §20',
  },
  {
    id: 'green_expenses',
    year: 2025,
    docSection: '§21',
    name: 'Green expenses',
    description:
      'EV charging facilities; domestic food waste composting machine (non-business use).',
    limit: { kind: 'fixed', amountRm: 2500 },
    category: 'other',
    icon: 'eco',
    taxSectionHint: 'YA 2025 · §21',
  },
  {
    id: 'housing_loan_interest_first_home',
    year: 2025,
    docSection: '§22',
    name: 'Housing loan interest (first home)',
    description:
      'SPA between 1 Jan 2025 – 31 Dec 2027. Relief depends on property price tier.',
    limit: {
      kind: 'tieredProperty',
      spaNote: '(SPA 2025-01-01 — 2027-12-31)',
      tiers: [
        { maxPriceRm: 500_000, capRm: 7000 },
        { maxPriceRm: 750_000, capRm: 5000 },
      ],
    },
    category: 'other',
    icon: 'home',
    taxSectionHint: 'YA 2025 · §22',
  },
]
